#!/usr/bin/env python3
"""Distill a deploy ``gains.yaml`` from a trained run's ``config.yaml``.

The per-joint PD gains, armature, friction, effort limit, default pose and action
scale a policy was trained with are part of its deploy contract: a checkpoint is
only valid with the gains it was trained on. They already travel with every model
(``config.yaml`` next to the ONNX); this script flattens the relevant fields into a
compact, name-keyed ``gains.yaml`` that the C++ deploy repos (arena,
spqrbooster2026) load at runtime instead of hardcoding.

  pixi run export-gains models/t1-velocity-manu/jun19_1
  pixi run export-gains models/t1-velocity-manu/*        # backfill every version

Output (one field per line, joint-name keyed -> robust to joint-order drift):

  Left_Hip_Pitch.kp: 33.09
  Left_Hip_Pitch.kd: 3.950
  Left_Hip_Pitch.armature: 0.052391
  Left_Hip_Pitch.frictionloss: 0.03
  Left_Hip_Pitch.effort_limit: 90.0
  Left_Hip_Pitch.default_pos: -0.24
  Left_Hip_Pitch.action_scale: 0.6799
"""

from __future__ import annotations

import sys
from pathlib import Path

import tyro
import yaml
from loguru import logger

# frictionloss is left null in config.yaml (the value lives in the robot XML); the
# deploy repos use this constant, so emit it when config does not pin a value.
DEFAULT_FRICTIONLOSS = 0.03

# Fields, in emit order. Documented here so both consumers agree on the schema.
FIELDS = ("kp", "kd", "armature", "frictionloss", "effort_limit", "default_pos", "action_scale")


def _find_actuators(node: object) -> list[dict] | None:
  """Return the first ``actuators`` list found anywhere in the config tree.

  Path-robust: we search by key rather than hardcoding the (deep, mjlab-versioned)
  ``task.env...articulation.actuators`` path.
  """
  if isinstance(node, dict):
    acts = node.get("actuators")
    if isinstance(acts, list) and acts and isinstance(acts[0], dict) and "target_names_expr" in acts[0]:
      return acts
    for v in node.values():
      found = _find_actuators(v)
      if found is not None:
        return found
  elif isinstance(node, list):
    for v in node:
      found = _find_actuators(v)
      if found is not None:
        return found
  return None


def _find_default_pos(node: object, joint_names: set[str]) -> dict[str, float]:
  """Return the ``joint_pos`` dict whose keys are concrete joint names.

  Several ``init_state.joint_pos`` blocks exist (env- and entity-level), and some
  use regex keys (``.*``). We pick the one that best matches the actuator joints.
  """
  best: dict[str, float] = {}
  best_score = -1

  def visit(n: object) -> None:
    nonlocal best, best_score
    if isinstance(n, dict):
      jp = n.get("joint_pos")
      if isinstance(jp, dict):
        score = sum(1 for k in jp if k in joint_names)
        if score > best_score:
          best, best_score = jp, score
      for v in n.values():
        visit(v)
    elif isinstance(n, list):
      for v in n:
        visit(v)

  visit(node)
  return best


def _gains_from_config(config_path: Path) -> dict[str, dict[str, float]]:
  cfg = yaml.safe_load(config_path.read_text())

  actuators = _find_actuators(cfg)
  if not actuators:
    raise ValueError(f"{config_path}: no actuators block found")

  # joint -> raw actuator entry (one joint per actuator in colosseum's set).
  per_joint: dict[str, dict] = {}
  for act in actuators:
    for joint in act["target_names_expr"]:
      per_joint[joint] = act

  default_pos = _find_default_pos(cfg, set(per_joint))

  gains: dict[str, dict[str, float]] = {}
  for joint, act in per_joint.items():
    kp = float(act["stiffness"])
    effort = float(act.get("saturation_effort") or act["effort_limit"])
    friction = act.get("frictionloss")
    gains[joint] = {
      "kp": kp,
      "kd": float(act["damping"]),
      "armature": float(act["armature"]),
      "frictionloss": DEFAULT_FRICTIONLOSS if friction is None else float(friction),
      "effort_limit": float(act["effort_limit"]),
      "default_pos": float(default_pos.get(joint, 0.0)),
      # booster_train recipe: action_scale * kp = 0.25 * peak torque.
      "action_scale": 0.25 * effort / kp,
    }
  return gains


def _write_gains_yaml(gains: dict[str, dict[str, float]], out_path: Path) -> None:
  lines = [
    "# Auto-generated by export_gains.py from config.yaml. Do not edit by hand.",
    "# Deploy contract: load by joint name (order-independent). Fields per joint:",
    f"# {', '.join(FIELDS)}",
    "",
  ]
  for joint, vals in gains.items():
    for field in FIELDS:
      lines.append(f"{joint}.{field}: {vals[field]:.6g}")
  out_path.write_text("\n".join(lines) + "\n")


def export_gains(model_dir: Path) -> Path | None:
  """Write ``<model_dir>/gains.yaml`` from ``<model_dir>/config.yaml``.

  Returns the gains.yaml path, or None if no config.yaml is present.
  """
  config_path = model_dir / "config.yaml"
  if not config_path.exists():
    logger.warning(f"skip {model_dir}: no config.yaml")
    return None
  gains = _gains_from_config(config_path)
  out_path = model_dir / "gains.yaml"
  _write_gains_yaml(gains, out_path)
  logger.info(f"wrote {out_path} ({len(gains)} joints)")
  return out_path


def main(model_dirs: tyro.conf.Positional[list[str]]) -> None:
  """Write gains.yaml into each given model directory.

  Args:
    model_dirs: one or more model directories (each containing config.yaml).
  """
  n = sum(export_gains(Path(d)) is not None for d in model_dirs)
  if n == 0:
    logger.error("no gains.yaml written")
    sys.exit(1)


if __name__ == "__main__":
  tyro.cli(main)
