site_name: Colosseum
site_description: Colosseum Documentation
copyright: "2025, Colosseum Team"
site_url: https://neverorfrog.github.io/colosseum/
repo_url: https://github.com/neverorfrog/colosseum.git
repo_name: neverorfrog/colosseum

nav:
  - Overview: index.md
  - COLOSSEUM:
      - Setup: colosseum/setup.md
      - Getting Started: colosseum/getting_started.md
      - Training & Evaluation: colosseum/training.md
      - Deployment (Arena): colosseum/deployment.md
      - Colosseum Internals: colosseum/internals.md
      - Dribbling Task Tutorial: colosseum/dribbling_tutorial.md
      - Cartpole Tutorial: colosseum/cartpole.md
  - MJLAB:
      - Overview: mjlab/overview.md
      - Task Layer: mjlab/task_layer.md
      - Scene & Simulation: mjlab/scene_simulation.md
  - Research:
      - Dribbling: research/dribbling.md
      - Soccer Maze: research/soccer-maze.md

theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo_bw.png
  font:
    text: Red Hat Text
    code: JetBrains Mono

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.code.annotate
    - content.tooltips
    - content.code.select
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.footer

  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css
