[project]
name = "colosseum"
version = "0.1.0"
requires-python = "==3.11.*"

# ============================================
# PIXI WORKSPACE CONFIGURATION
# ============================================
[tool.pixi.workspace]
channels = ["conda-forge", "robostack-jazzy"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tool.pixi.dependencies]
pytest = ">=9.0.1,<10"
ros-jazzy-desktop = ">=0.11.0,<0.12"

[tool.pixi.pypi-dependencies]
colosseum = {path = ".", editable = true}
mujoco = ">=3.3.8.dev836680575,<4"

[tool.pixi.environments]
default = ["train"]
deploy = {features = ["deploy"]}
docs = { features = ["docs"], no-default-feature = true, solve-group = "default" }

# ============================================
# TRAIN FEATURE
# ============================================
[tool.pixi.feature.train.pypi-dependencies]
mjlab = {git = "https://github.com/mujocolab/mjlab.git", branch = "main"}

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"

[project.entry-points."mjlab.tasks"]
cartpole = "colosseum.tasks.cartpole"
velocity = "colosseum.tasks.velocity"

# ============================================
# DEPLOY FEATURE
# ============================================
[tool.pixi.feature.deploy.dependencies]
booster_robotics_sdk = {git = "https://github.com/neverorfrog/booster_robotics_sdk.git", branch = "main"}
cuda-version = "12.6.*"
pytorch-gpu = "*"

[tool.pixi.feature.deploy.system-requirements]
cuda = "12.0"

# ============================================
# DOCS FEATURE
# ============================================
[tool.pixi.feature.docs.dependencies]
mkdocs-material = ">=9.6.14,<10"

[tool.pixi.feature.docs.tasks]
build-docs = "mkdocs build --strict"
docs = { cmd = "mkdocs serve", description = "Serve the docs locally" }

# ============================================
# OTHER TOOLS
# ============================================
[tool.ty.environment]
extra-paths = ["typings"]

[tool.ty.src]
include = ["src", "tests"]
exclude = ["typings", "models"]

[tool.ruff]
src = ["src"]
indent-width = 2
