# ============================================
# PROJECT CONFIGURATION
# ============================================
[project]
name = "colosseum"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
	"ty>=0.0.1a34,<0.0.1a35",
	"pydantic>=2.12.5,<3",
	"evdev>=1.9.2,<2",
	"tyro>=1.0.1,<2",
	"pytest>=8.0.2,<10",
]

[tool.pixi.workspace]
channels = [
	"https://prefix.dev/pixi-build-backends",
	"robostack-humble",
	"conda-forge",
]
platforms = ["linux-64", "linux-aarch64"]
preview = ["pixi-build"]

# ============================================
# TRAIN FEATURE
# ============================================
[tool.pixi.environments.train]
features = ["train"]
no-default-feature = true
solve-group = "train"

[tool.pixi.feature.train]
platforms = ["linux-64"]

[tool.pixi.feature.train.dependencies]
python = "3.11.*"
pytest = ">=9.0.1,<10"
pytorch-gpu = "*"
onnxruntime = ">=1.22.2,<2"

[tool.pixi.feature.train.system-requirements]
cuda = "12.0"

[tool.pixi.feature.train.pypi-dependencies]
colosseum = {path = ".", editable = true}
mjlab = {git = "https://github.com/mujocolab/mjlab.git", branch = "main"}

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"

[project.entry-points."mjlab.tasks"]
cartpole = "colosseum.tasks.cartpole"
velocity = "colosseum.tasks.velocity"

[tool.pixi.feature.train.tasks]
train = "python -m mjlab.scripts.train"
play = "python -m mjlab.scripts.play"
deploy = "python -m colosseum.scripts.deploy_tyro"
export-onnx = { cmd = "python -m colosseum.scripts.export_onnx"}

# ============================================
# ROBOT FEATURE
# ============================================
[tool.pixi.environments.robot]
features = ["robot"]
no-default-feature = true
solve-group = "robot"

[tool.pixi.feature.robot]
platforms = ["linux-aarch64"]

[tool.pixi.feature.robot.dependencies]
python = "3.9.*"
booster_robotics_sdk = {path = "external/booster_robotics_sdk"}
nanobind = ">=2.4,<3"

[tool.pixi.feature.robot.pypi-dependencies]
colosseum = {path = ".", editable = true}
torch = "*"
torchvision = "*"

[tool.pixi.feature.robot.tasks]
gen-booster-stubs = { cmd = "python -m nanobind.stubgen -m booster_robotics_sdk_python -o typings/booster_robotics_sdk_python.pyi", description = "Generate stubs for booster_robotics_sdk_python into typings/" }

# ============================================
# ROSSIM FEATURE
# ============================================

[tool.pixi.environments.rossim]
features = ["rossim"]
no-default-feature = true
solve-group = "rossim"

[tool.pixi.feature.rossim]
platforms = ["linux-64"]

[tool.pixi.feature.rossim.dependencies]
python = "3.9.*"
ros-humble-rclpy = ">=3.3.4,<4"
ros-humble-rmw-fastrtps-cpp = "*"
ros-humble-rmw-fastrtps-dynamic-cpp = "*"
ros-humble-rosidl-typesupport-fastrtps-c = "*"
ros-humble-rosidl-typesupport-fastrtps-cpp = "*"
ros-humble-rosidl-runtime-py = "*"
tinyxml2 = "==9"

[tool.pixi.feature.rossim.pypi-dependencies]
colosseum = {path = ".", editable = true}
tyro = ">=1.0.1,<2"
pydantic = ">=2.12.5,<3"
evdev = ">=1.9.2,<2"

# ============================================
# DOCS FEATURE
# ============================================

[tool.pixi.environments.docs]
features = ["docs"]
no-default-feature = true
solve-group = "docs"

[tool.pixi.feature.docs.dependencies]
mkdocs-material = ">=9.6.14,<10"

[tool.pixi.feature.docs.tasks]
build-docs = "mkdocs build --strict"
docs = { cmd = "mkdocs serve", description = "Serve the docs locally" }

# ============================================
# OTHER TOOLS
# ============================================
[tool.ty.environment]
extra-paths = ["typings"]

[tool.ty.src]
include = ["src", "tests"]
exclude = ["typings", "models"]

[tool.ruff]
src = ["src"]
indent-width = 2
